#! /bin/sh
#
# chkconfig: - 86 16
#
### BEGIN INIT INFO
# Provides:        pingfederate
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: PingFederate
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

JAVA_DIR=/usr/lib/jvm/java-6-sun

JAVA_HOME=$JAVA_DIR
export JAVA_HOME

NAME=pingfederate
DESC="PingFederate"
DAEMON=$JAVA_DIR/bin/java
PIDFILE=/var/run/$NAME.pid
RUNASUSER=pingfed

PING_DIR=/usr/local/pingfederate
START_SH=$PING_DIR/sbin/pingfederate-run.sh
STOP_SH=$PING_DIR/sbin/pingfederate-shutdown.sh

test -x $JAVA_DIR/bin/java || exit 5

d_start() {
	#start-stop-daemon --start --chuid $RUNASUSER --exec $START_SH
	start-stop-daemon --start --exec $START_SH
	RETVAL="$?"
	return $RETVAL
}

d_stop() {
	#start-stop-daemon --start --chuid $RUNASUSER --exec $STOP_SH
	start-stop-daemon --start --exec $STOP_SH
	RETVAL="$?"
	return $RETVAL
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		if d_start; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		if d_stop; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	restart|force-reload)
		echo -n "Restarting $DESC" "$NAME"
		d_stop
		sleep 10
		d_start
		echo "."
		;;
	*)
		log_action_msg "Usage: $0 {start|stop|restart|force-reload}"
		exit 2
	;;
esac

exit 0
